data <- read.table("household_power_consumption.txt", sep = ";", header = TRUE)
d1 <- subset(data, Date == "1/2/2007"| Date == "2/2/2007")
attach(d1)
hist(as.numeric(as.vector(Global_active_power)), col="red", xlab="Global Active Power (kilowatts)", main = "Global Active Power")
dev.copy(png, file = "plot1.png")
dev.off()