data <- read.table("household_power_consumption.txt", sep = ";", header = TRUE)
d1 <- subset(data, Date == "1/2/2007"| Date == "2/2/2007")
d1$Date <- paste(d1$Date, d1$Time)
d1$Date <- strptime(d1$Date, format = "%d/%m/%Y %H:%M:%S")
par(mfcol = c(1,1))
plot(d1$Date, as.numeric(as.vector(d1$Sub_metering_1)), type="n", ylab = "Energy sub metering", xlab="")
lines(d1$Date,as.numeric(as.vector(d1$Sub_metering_1)))
lines(d1$Date,as.numeric(as.vector(d1$Sub_metering_2)), col = "red")
lines(d1$Date,as.numeric(as.vector(d1$Sub_metering_3)), col = "blue")
legend("topright", legend= c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty = 1, col=c("black", "red", "blue"), cex = 0.7, inset =0)
dev.copy(png, file = "plot3.png")
dev.off()