data <- read.table("household_power_consumption.txt", sep = ";", header = TRUE)
d1 <- subset(data, Date == "1/2/2007"| Date == "2/2/2007")
d1$Date <- paste(d1$Date, d1$Time)
d1$Date <- strptime(d1$Date, format = "%d/%m/%Y %H:%M:%S")
par(mfcol = c(2,2))
plot(d1$Date, as.numeric(as.vector(d1$Global_active_power)), type="l", ylab = "Global Active Power (kilowatts)", xlab="")
plot(d1$Date, as.numeric(as.vector(d1$Sub_metering_1)), type="n", ylab = "Energy sub metering", xlab ="")
lines(d1$Date,as.numeric(as.vector(d1$Sub_metering_1)))
lines(d1$Date,as.numeric(as.vector(d1$Sub_metering_2)), col = "red")
lines(d1$Date,as.numeric(as.vector(d1$Sub_metering_3)), col = "blue")
legend("topright", legend= c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty = 1, col=c("black", "red", "blue"), cex = 0.25)
plot(d1$Date,as.numeric(as.vector(d1$Voltage)), type = "l", ylab = "Voltage", xlab="datetime")
plot(d1$Date,as.numeric(as.vector(d1$Global_reactive_power)), type = "l", ylab = "Global_reactive_power", xlab="datetime")
dev.copy(png, file = "plot4.png")
dev.off()
